name: Build Flutter Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: flutter-web-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Create web platform
        run: flutter create --platforms=web .

      - name: Build Flutter Web
        run: flutter build web --release --pwa-strategy offline-first --base-href "/Tajweed-Master/"

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tajweed-master-web
          path: build/web

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
